### ISSUE TITLE
How to add objects

### ISSUE THREAD

**Issue by zhuozhuo** [robbykraft/Panorama#19]

**Comment by autresphere** [comment]
Hi,
Any news about this screenLocationFromVector method?
Thanks in advance.

**Comment by autresphere** [comment]
Here is some code that returns the location on screen from a 3D point:

```
- (BOOL)computeScreenLocation:(CGPoint*)location fromVector:(GLKVector3)vector inAttitude:(GLKMatrix4)matrix
{
    GLKVector4 screenVector;
    GLKVector4 vector4;

    if(location == NULL)
        return NO;
    
    matrix = GLKMatrix4Multiply(_projectionMatrix, matrix);
    vector4 = GLKVector4Make(vector.x, vector.y, vector.z, 1);
    screenVector = GLKMatrix4MultiplyVector4(matrix, vector4);

    location->x = (screenVector.x/screenVector.w/2.0 + 0.5) * self.frame.size.width;
    location->y = (0.5-screenVector.y/screenVector.w/2) * self.frame.size.height;
    
    return (screenVector.z >= 0);
}
```
This method returns wether the point is before or behind the screen.
It does work in portrait but would need some additional code to take care of all orientations.
I will create a PR if I find some time.

**Comment by robbykraft** [comment]
it actually works fine with orientations, it alerted me to another issue- orientation handling is being over-complicated, fixing it now.
