### ISSUE TITLE
park_2048.jpg This panorama photo is how to do it?

### ISSUE THREAD

**Issue by ninki51** [robbykraft/Panorama#20]
park_2048.jpg This panorama photo is how to do it?

**Comment by robbykraft** [comment]
sorry, I'm having trouble understanding- how to do it? What are you trying to do?

**Comment by autresphere** [comment]
If your question is how to create a panorama image, then you can use 2D/3D softwares. Photoshop, After Effects or Blender for example have the ability to create an "equirectangular projection".

**Comment by ninki51** [comment]
thanks
