### ISSUE TITLE
Panorama 2d

### ISSUE THREAD

**Issue by rzehan** [robbykraft/Panorama#22]
Hi Robby,

First of all thanks for this great resource, is making my life easier :)
One question I have: how can I adapt the view to show panoramic images only on 2 axes (e.g. without Y motion) ?

Thanks,
Rares

**Comment by robbykraft** [comment]
Good suggestion, Rares!
I can imagine something like:
`[panoramaView setYMotionEnabled:NO];`

for the moment, going inside the -(void)draw function in PanoramaView.m, line 166 for me, I was able to do this by inserting a call to `orientToAzimuth`

```
        _attitudeMatrix = GLKMatrix4Multiply([self getDeviceOrientationMatrix], _offsetMatrix);
        [self updateLook];

        [self orientToAzimuth:-_lookAzimuth Altitude:0];
        glMultMatrixf(_attitudeMatrix.m); 
```

**Comment by rzehan** [comment]
Awesome! It worked like you said.

Thanks
