### ISSUE TITLE
How to create a photo sphere

### ISSUE THREAD

**Issue by kiwi07** [robbykraft/Panorama#43]
Please tell me How to create a photo sphere like this
https://www.youtube.com/watch?v=NPs3eIiWRaw
Thank in advance.

**Comment by robbykraft** [comment]
Hi,
Sorry this isn't a recording tool, just a display tool.
This kind of technology works best with (or maybe requires) image stitching, something that would take some effort.
Sorry it's outside the scope of this project.
Robby
