### ISSUE TITLE
Spherical panorama corrugated 

### ISSUE THREAD

**Issue by shaojiankui** [robbykraft/Panorama#46]
i have try many libs for panorama，inluded yours Spherical panorama wiil let image appear corrugated 。
Spherical picture

The effect picture
![Uploading A5E5A313-D054-4DDD-96B4-DE7FD380CA8D.png…]()

but Others'cubic (six cube Map)panorama will not have this situation。the six cube Map From the Spherical picture transform

![Uploading C5E1B028-2461-46C0-A75A-4F7EF36703A6.png…]()

**Comment by robbykraft** [comment]
hi, your pictures aren't showing, can you re-post them?

are you referring to the corrugation effect that is visible at the poles?

**Comment by robbykraft** [comment]
discuss on #30
