### ISSUE TITLE
Swift integration problem

### ISSUE THREAD

**Issue by edwinsiu** [robbykraft/Panorama#49]
![screen shot 2016-08-19 at 1 16 43 pm](https://cloud.githubusercontent.com/assets/5013479/17799693/364d110e-660f-11e6-8ac7-d91026e3397a.png)

Your library looks good.

But when I try to integrate it into my project, it fails that it requires me to import GLKit.

After I add it manually into the library, it works

Is there any way to solve it becoz whenever I update cocoapods, i have to edit this part.

Thank you so much!!~

**Comment by Dover8** [comment]
The following line needs added to the top of PanoramaView.h
`#import <GLKit/GLKit.h>`
And then of course the frameworks need added in the build settings.
