### ISSUE TITLE
PanGesture only change azimuth without change Y motion

### ISSUE THREAD

**Issue by bochitan** [robbykraft/Panorama#53]
Hi Robby,

First of all, thanks for great source.

I use both of setOrientToDevice and setTouchToPan with 3D panorama image.
setOrientToDevice work great, change azimuth and Y motion.
However, about TouchPanGesture, i want to change only azimuth without change Y motion.

Can you help me how to get that?

Thanks

**Comment by robbykraft** [comment]
Hi!
Thanks, yes this is now in the library, set:
```
[panoramaView setLockPanToHorizon:YES];
```
Hope it helps!
Robby
