### ISSUE TITLE
VR mode on iphone7+

### ISSUE THREAD

**Issue by tommylch** [robbykraft/Panorama#54]
I integrated the viewer to my app using a GLKViewcontroller. While I switch to VR mode in iphone7+, two eyes is not in the same size? Is the any code I need to adjust?

**Comment by robbykraft** [comment]
Yes, thank you! I've found the same issue, it's because of `[UIScreen mainScreen].scale` instead of `[UIScreen mainScreen].nativeScale`

Fixed in 6bb717a576a1005b5049470180bae76de9ba6111
