### ISSUE TITLE
how to make data from coremotion right just like facebook panorama photo in feed and switch to big picture still work right?

### ISSUE THREAD

**Issue by niuxinghua** [robbykraft/Panorama#57]

**Comment by robbykraft** [comment]
Hi,
Sorry I can't tell exactly what you're asking. Can you elaborate?

If you are referring to the feature where it doesn't move up or down, you can use:
```
[panoramaView setLockPanToHorizon:YES];
```

**Comment by niuxinghua** [comment]
thanks very much  i have solved it
