### ISSUE TITLE
Set Image directly instead of name/path

### ISSUE THREAD

**Issue by ecristerna** [robbykraft/Panorama#63]
Is there any way of setting the image by giving it the UIImage, instead of the name or path?

**Comment by nguyenkhanhtoan94** [comment]
UIImage *image = [UIImage alloc] init]; //Set UIImage you want
 [panoramaView setImage:image];
But don't do that twice in the same runtime. Image is maybe flipped.

**Comment by bochitan** [comment]
Yes, you can use setImage method inside Panorama class.
I used this method already.

Have fun
