### ISSUE TITLE
adapting image orientation with device orientation

### ISSUE THREAD

**Issue by sassiwalid** [robbykraft/Panorama#64]
HI ROBBY,
thank you for this great panorama library. I would like to ask it's possible to adapt image show with the device orientation. if the device is oriented to north, we get the north of the 360° image something like in facebook App.

**Comment by robbykraft** [comment]
so sorry for missing this, I like this idea a lot!
is this information encoded in the metadata of certain image formats?
either way we would need to allow the user to manually set the north point. like for instance, which percent of the image 0.0 to 1.0 is the direction of north. 
for example `view.setNorth(0.2)`
basically the same as #65

**Comment by mayakraft** [comment]
new property: cardinalOffset. updated in 3caaedc8c7f36eae100213cc20705f91f0aacf68
