### ISSUE TITLE
How can I set the current viewing direction to the center of the image?

### ISSUE THREAD

**Issue by miyurusagarage** [robbykraft/Panorama#65]
I want to set the current viewing direction to the center of the image using a button. How can I achieve this?

**Comment by robbykraft** [comment]
this is a good idea. i'm imagining a function that adds a rotation around the vertical poles to the offsetMatrix or something like it, perhaps called something like

```
-(void)setImageOffsetLongitude:(float)longitude
```

immediately, it can be hacked by adding a rotateY(amount) right before the sphere draw command

**Comment by mayakraft** [comment]
new property: cardinalOffset. updated in 3caaedc8c7f36eae100213cc20705f91f0aacf68
