### ISSUE TITLE
How to Use the Panorama View for UIView?

### ISSUE THREAD

**Issue by InquirerMegamobileInc** [robbykraft/Panorama#66]
Hello, 

How will i use the panorama view inside uiview? thanks. 

Thanks.

**Comment by robbykraft** [comment]
Unless there is a workaround I'm not familiar with, you need a GLKViewController.

here's a suggestion that might help https://stackoverflow.com/questions/10224257/integrate-uiview-and-glkview-inside-of-uiviewcontroller/12906856

I haven't tried it but it sounds like it allows for a windowed GLKViewController surrounded by a UIView+UIViewController
