### ISSUE TITLE
Camera Features Support

### ISSUE THREAD

**Issue by shadow111** [robbykraft/Panorama#67]
Hello,
please is tis app include camera support like the one in the google street view where the user can take photo by pointing   the camera to dot.
Thank you
Lafi

**Comment by robbykraft** [comment]
Do you mean image-stitching to create a panorama image using the camera?

**Comment by shadow111** [comment]
yes using the camera, like google street view where some dot are displayed and you need to pint a circle in the dot to take picture, then you have to turn the phone arround 
like this video : https://www.youtube.com/watch?v=-JN8iex0yG8

**Comment by robbykraft** [comment]
Hi Sorry I didn't follow up. This project isn't for recording, just displaying. 
It would involve photo stitching, and a lot of image processing stuff that would be necessary. Lots of people are asking for this, #43, it would be a lot of code and expand the project into kind of a different one.
