### ISSUE TITLE
Large Image not loading.

### ISSUE THREAD

**Issue by vijayradke** [robbykraft/Panorama#69]
Hello, 
My Image size is more than 40 MB and it is not loading in Panorama view. Just showing white screen.
Can anyone face this kind of issue?
Appreciate for any kind of help. 
Thanks.

**Comment by robbykraft** [comment]
Hi @vijayradke do the image dimensions conform to the list of powers of 2 for OpenGL textures?

acceptable image sizes: (4096×2048), 2048×1024, 1024×512, 512×256, 256×128 ...

**Comment by vijayradke** [comment]
Hi @robbykraft thanks for quick response. It resolved my issue.
