### ISSUE TITLE
hotspot feature

### ISSUE THREAD

**Issue by alann-maulana** [robbykraft/Panorama#7]
Thanks for your great code. It would be great if it has hotspot feature :+1:

**Comment by phantomlight** [comment]
Hello robbykraft thank you so much for this! works great in my app. I'm trying to get hotspots to work. Not sure if anyone was able to get it working. Pretty much added a button and when the button is pressed depending on the coordinates set should change the view inside the image. Any idea?

**Comment by robbykraft** [comment]
hello @phantomlight 
did you try this function:
```
/**
 * Hit-detection for all active touches
 *
 * @param CGRect defined in image pixel coordinates
 * @return YES if touch is inside CGRect, NO otherwise
 */
-(BOOL) touchInRect:(CGRect)rect;
```

This adds a button into the world. This is the function that people are calling a "hotspot". It moves with the panorama.

Adding a UIKit UIButton will not move around with the world, but sit in the same location on the screen.

Can you clarify again what you're trying to accomplish?
