### ISSUE TITLE
EXC_BAD_ACCESS on iOS 11

### ISSUE THREAD

**Issue by AlanFloyd** [robbykraft/Panorama#72]
Tested on Simulator and iPhone 6 with iOS 10. All working fine. Also attached own photos, everything fine. BUT, when using iPhone 6s plus and iOS 11, I am getting EXC_BAD_ACCESS (code=2, address0x19a948ad8). Any idea how to fix it?

I used Xcode 8 and 9 (beta) and both are giving the same error.

**Comment by robbykraft** [comment]
hello, sorry I haven't been around.

Is this still happening? I haven't been able to replicate the error. I'm running all the newest versions on everything.

I just updated the cocoapod to version 1.0.2, there was an #include file bug that was fixed

**Comment by AlanFloyd** [comment]
Hello Robby,

thanks for the contact. I have changed to another tool, anyhow will make some tests if I still can produce the error or not. Let you know.

Best Season Greetings from Mexico

Saludos

Dietmar Schwarz Webers
dietmar.schwarz@icloud.com

Desarrollando y Capacitando para iOS
www.dswdev.com

**Comment by robbykraft** [comment]
hmm, I wonder if it has to do with the image/texture, but just a guess.
No worries if you can't get to it but I'll be curious if you do.
thanks! happy holidays to you too

**Comment by robbykraft** [comment]
heads up, just saw this was an error on #55 they were using in a non-native environment (Titanium) and it had to do with the file paths being all wrong in the new environment and not actually loading the texture.
I would check the texture data after it's loaded to make sure it loaded properly
