### ISSUE TITLE
Unable to build pod in swift project

### ISSUE THREAD

**Issue by rpcarson** [robbykraft/Panorama#75]
Hey, I added use_frameworks! and pod installed just like usual but the pod has several errors and I am also getting a "could not build objective c module" error for the import statement.

**Comment by robbykraft** [comment]
Hi Reed,
Yes I need to update the cocoapod.

It should remove that error and build if you add one line at the top of PanoramaView.h

```
#import <GLKit/GLKit.h>
```

**Comment by robbykraft** [comment]
btw, this fix is now live on cocoapods, v 1.0.2
